name: Build PR Image

on: issue_comment

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github) }}'

  build:
    runs-on: ubuntu-latest

    if: |
      github.event.issue.pull_request && contains(github.event.comment.body, '/build-docker-image') &&
      ( github.event.comment.author_association == 'MEMBER' ||  github.event.comment.author_association == 'OWNER')

    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
            arguments: distTar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: target/emoji_manager
          tags: type=raw,value=pr-${{ github.event.issue.number }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



