name: Test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
   testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: sudo systemctl start postgresql.service ; pg_isready
      - run: cat db-migration/initdb.d/01_docker-bootstrap.sql | sudo -u postgres psql -f -
      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        env:
          DATABASE_HOST: localhost
        with:
          arguments: check



